### ISSUE TITLE
Dead link on Plotting functions overview.

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaPlots/MakieGallery.jl#107]
From this page: https://github.com/JuliaPlots/MakieGallery.jl/blob/master/docs/src/index.md

If I click  "Plotting functions overview", I get an error 404 page not found. 

This looks like the desired page: https://github.com/JuliaPlots/MakieGallery.jl/blob/master/docs/src/src-functions.md

But it's not clear how all of the functions get here if there's no reference to them on that link above.

**Comment by asinghvi17** [comment]
They are auto generated, check `docs/make.jl` to see how.

**Comment by logankilpatrick** [comment]
Okay, I see that, but still not sure how to fix this issue.
