### ISSUE TITLE
Ambiguity around scene parent relationship

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaPlots/MakieGallery.jl#111]
In my code, I never declare a `Scene` explicitly. Does that mean that the first thing I declare(ex. a `line()`) is the parent?

**Comment by SimonDanisch** [comment]
non mutating plot commands are implemented as:
```Julia
lines(args...) = lines!(Scene(), args...)
```
So yes, lines will then return the newly created scene, which becomes the parent of all following `plot!` commands
