### ISSUE TITLE
Transformations page is broken

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaPlots/MakieGallery.jl#126]
http://makie.juliaplots.org/dev/transformations.html# does not actually work.

**Comment by logankilpatrick** [comment]
Maybe this is a lack of understanding on my part, but wouldn't the reason for this issue occurring be that `transformations.md` is not in the `make.jl` file? @asinghvi17

**Comment by asinghvi17** [comment]
yeah that would be a problem.  Frankly, I'm not even sure why it's up...

**Comment by asinghvi17** [comment]
The problem with that page was that it needed to have the transformation docstrings, and you can only put those in one place...but the Scene page also needed them.
