### ISSUE TITLE
The `@substep` macro is not documented in examples but not found on the docs

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaPlots/MakieGallery.jl#135]
I do not see where the `@substep` macro is defined. yet it is used places like #134

**Comment by asinghvi17** [comment]
https://github.com/JuliaPlots/MakieGallery.jl/blob/4f62daa745c3ffaa3cafefe2946d8e19bad626c5/src/documenter_extension.jl#L45-L46

**Comment by asinghvi17** [comment]
That's because the `@substep` macro _should_ be internal.  The StatsMakie examples use it mainly - it just breaks an example up into many sub-examples, which are individually addressable.  This allows you to load data once, but create multiple example blocks.
