### ISSUE TITLE
More clear docs on how to add something to the Example Gallery

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaPlots/MakieGallery.jl#148]
Hey @asinghvi17 , I am trying to add something to the example gallery, so I can do this `@example_database("Tutorial adding to a scene")` with my own example in the docs. How do I get it into there? 

Do I just do 

```
@cell "$title" [labels...] begin
    # example code here
end

```

Where the title is the `@example_database("title")`?

**Comment by SimonDanisch** [comment]
Yeah, but no $ in `$title` ;)  Also, it needs to be in a `@block` block ;)

**Comment by logankilpatrick** [comment]
I don't see where the `"Tutorial adding to a scene"` example is in the repo. Can you direct me to it ?

**Comment by logankilpatrick** [comment]
I found it. In the example on the docs, it has images. but in the actual code, there's no reference to images. How do I get the images to show?

**Comment by SimonDanisch** [comment]
What do you mean? If you insert an example via `@example_database("title")` in the docs, it will generate images in the final docs, but not in the markdown files.
