### ISSUE TITLE
Vbox and Hbox ASCII examples don't show properly

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaPlots/MakieGallery.jl#155]
see: http://makie.juliaplots.org/dev/functions-overview.html#vbox-1

vs 

https://github.com/JuliaPlots/AbstractPlotting.jl/blob/27697b4045c62a5c7a1c868403949dfb84d752b6/src/layouting/layouting.jl#L176-L186

Can we add "\n" or something like that to get multiple lines?

**Comment by asinghvi17** [comment]
Just did that in JuliaPlots/AbstractPlotting.jl#211

**Comment by logankilpatrick** [comment]
awesome!
