### ISSUE TITLE
Unclear how to change the default size of a makie window

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaPlots/MakieGallery.jl#156]
When I set the resolution of a scene, the size of the makie window does not change, so how do I change the window size?

**Comment by SimonDanisch** [comment]
Uh, `resize!(scene, ...)` is intended to do so, but doesn't seem to work correctly...
This works though:
```Julia
scene = ...
screen  = display(scene)
resize!(screen, 500, 400)
```

**Comment by logankilpatrick** [comment]
what does the `resolution` attribute do then?

**Comment by SimonDanisch** [comment]
Wait, what are you exactly trying to do? I see, that there seem to be 2 different things you're trying to do between the title and your comment.

**Comment by logankilpatrick** [comment]
We resolved my confusion in person Haha
