### ISSUE TITLE
[Documentation] What keyboard buttons are available? 

### ISSUE THREAD

**Issue by aminya** [JuliaPlots/MakieGallery.jl#165]
Here in documentation http://makie.juliaplots.org/dev/scenes.html#Events-1 it says some keyboard buttons are supported for interaction, but not mentioned what are those. Same for mouse clicks (left or right click, etc)

**Comment by SimonDanisch** [comment]
Mouse and Keyboard is a module & enum, so autocomplete etc should work nicely:
https://github.com/JuliaPlots/AbstractPlotting.jl/blob/master/src/interaction/iodevices.jl

**Comment by aminya** [comment]
It would be nice to at least add a link to this part of the code to the documentation.
