### ISSUE TITLE
several pages need updating

### ISSUE THREAD

**Issue by fungktt** [JuliaPlots/MakieGallery.jl#176]
There’s a link in the marker_offset section in [this page](http://makie.juliaplots.org/dev/plot-attributes.html#List-of-attributes-1) that needs fixing.
It doesn't actually lead to the example.

Also [this page](http://makie.juliaplots.org/dev/transformations.html#) about Transformation is missing docstring.

**Comment by asinghvi17** [comment]
The transformation page shouldn't really exist, I'm not sure how it got there.  Will fix the link, though - thanks!
