### ISSUE TITLE
Cache `.julia` during tests

### ISSUE THREAD

**Issue by asinghvi17** [JuliaPlots/MakieGallery.jl#54]
Downloading registries and packages into`.julia` during CI takes a decent amount of time...I wonder if we could cache it using Gitlab CI's caching features?  I should have some spare time on my hands in a week or so to do it.

**Comment by SimonDanisch** [comment]
I don't think we should try that... Too much work to just shave a few mins of the tests. This may also introduce lots of problems with the Package manager and having weird versions stick around, so I really don't think we should try this ;)
