### ISSUE TITLE
Moving test infrastructure around

### ISSUE THREAD

**Issue by asinghvi17** [JuliaPlots/MakieGallery.jl#66]
https://github.com/JuliaPlots/MakieGallery.jl/blob/e36d377449b15ffbae8b42a9a42e13309dfc01bd/src/testruns.jl#L79-L117

Do we need this as a function, or could it be copy-pasted into `test/runtests.jl`?  ~For some reason, the testsets don't show...~ Nevermind, found it.

**Comment by SimonDanisch** [comment]
This needs to be in MakieGallery, since all other Packages use this function as well!
