### ISSUE TITLE
Examples which print too much

### ISSUE THREAD

**Issue by asinghvi17** [JuliaPlots/MakieGallery.jl#70]
- [x] Printing `Scene`s as text
    - [x] `tutorial_title`
    - [x] `image_on_geometry__earth_`
    - [x] `surface___wireframe___contour` (also seems to have a `@time` somewhere in there)
- [x] Curl downloads
    - [x] `image_on_geometry__moon_`
    - [x] `image_on_geometry__earth_`
    - [x] `earth___ships` (why?  could be `robot_arm`)
    - [x] `worldclim_visualization`

**Comment by asinghvi17** [comment]
@mortenpi was kind enough to provide this link to a function which suppresses all stdout and stderr output.  We could probably copy this and use it to wrap the `eval_example`s...

**Comment by SimonDanisch** [comment]
Nooo, that'd make it too easy to oversee real issues! If it's annoying, which should fix the examples ;)

**Comment by asinghvi17** [comment]
Fair enough, we could call `display(PlotDisplay(), Scene)` instead of `scene` to help with that at least
