### ISSUE TITLE
Running the slider example code produces no output. 

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaPlots/MakieGallery.jl#79]
When I run this code, https://simondanisch.github.io/ReferenceImages/gallery//sliders/index.html, Nothing occurs. Please add some comments or links to the code itself so I know what the expected output is and how to use the example.

**Comment by asinghvi17** [comment]
Try replacing abstractplotting with Makie?  I think that might be fixed on master but not propagated to ref images.

**Comment by logankilpatrick** [comment]
Okay, that did the trick

**Comment by logankilpatrick** [comment]
Works like a charm now!

**Comment by asinghvi17** [comment]
Leaving this open to remind me to make the change.

**Comment by logankilpatrick** [comment]
Just to put this out there in case you did not know, these issues affect more than just the example I mentioned here. https://simondanisch.github.io/ReferenceImages/gallery//image_on_geometry__earth_/index.html is effected and maybe more!

**Comment by logankilpatrick** [comment]
This appears to be fixed in the makie gallery.

**Comment by asinghvi17** [comment]
Yeah, that was fixed in the new reference images.
