### ISSUE TITLE
Document issues with plotting but not updating

### ISSUE THREAD

**Issue by asinghvi17** [JuliaPlots/MakieGallery.jl#80]
With reference to a conversation with @deXtoRious on Slack.  It seems that the scene needed to be explicitly displayed (or at least it needed to be fully updated) before plots constructed after the last `display(scene)` call would show.  Solution there was to preconstruct plots, but obviously that doesn't make sense for some situations.

**Comment by SimonDanisch** [comment]
I actually started fixing that - Need to figure out how to merge the changes, since they're a bit more destructive (not necessarily the one fixing this, but rather some other changes I put in the mix to prepare for better axes)....
