### ISSUE TITLE
Better documentation around Sliders

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaPlots/MakieGallery.jl#81]
I am trying to implement a basic slider. The examples in the Makie Gallery are a little more complex than I am looking for(the actual slider functionality is a little hidden under the complexity of the actual ting being plotted). The docs for sliders also just as a TODO as a place holder. If anyone has a simple slider example, I would appreciate seeing it. I will keep working on it for now.

**Comment by SimonDanisch** [comment]
Isn't this pretty simple: https://simondanisch.github.io/ReferenceImages/gallery//sliders/index.html ?
On master you can also just do this:
```
 s1 = slider(LinRange(0.01, 1, 100), start = 0.3)
 s2 = slider(LinRange(-2pi, 2pi, 100))
 data = lift(s2[end][:value]) do v
     map(LinRange(0, 2pi, 100)) do x
         4f0 .* Point2f0(sin(x) + (sin(x * v) .* 0.1), cos(x) + (cos(x * v) .* 0.1))
     end
 end
 p = scatter(data, markersize = s1[end][:value])
hbox(p, vbox(s1, s2))
```

**Comment by logankilpatrick** [comment]
It's not clear to me what that loop is doing.

**Comment by asinghvi17** [comment]
Check out the Animation and Interaction tutorials in the docs, those should give some more info...

**Comment by SimonDanisch** [comment]
Which loop? You mean:
```
map(LinRange(0, 2pi, 100)) do x
    4f0 .* Point2f0(sin(x) + (sin(x * v) .* 0.1), cos(x) + (cos(x * v) .* 0.1))
end
```
?
That just generates some data from the slider value....
You could also leave that and reduce the example to:
```julia
 s1 = slider(LinRange(0.01, 1, 100), start = 0.3)
 p = scatter(rand(4), markersize = s1[end][:value])
hbox(p, s1)
```

**Comment by logankilpatrick** [comment]
Ah, that is helpful thank you both!

**Comment by logankilpatrick** [comment]
I like the new updated docs related to sliders.
