### ISSUE TITLE
Example code for "Animation using time" in the docs does not work

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaPlots/MakieGallery.jl#86]
http://makie.juliaplots.org/stable/interaction.html#Animation-using-time-1

If you try running the code here ^, I get an error. 

```
#Example Plotting
using Makie

time = Node(0.0)

scene = Scene()
time = Node(0.0)
myfunc(v, t) = sin.(v, t)

scene = lines!(
    scene,
    lift(t -> f.(range(0, stop=2pi, length=50), t), time)
)

push!(time, Base.time())
```

`**ERROR: LoadError: UndefVarError: f not defined
Stacktrace:
 [1] (::getfield(Main, Symbol("##9#10")))(::Float64) at /Users/logankilpatrick/Desktop/TestPlotting.jl:12
 [2] lift(::Function, ::Observables.Observable{Float64}) at /Users/logankilpatrick/.julia/packages/AbstractPlotting/zoqRL/src/interaction/nodes.jl:9
 [3] top-level scope at none:0**`

**Comment by asinghvi17** [comment]
Could have sworn I updated that, try replacing `f` with `myfunc`?

**Comment by logankilpatrick** [comment]
I did and I got 
```
ERROR: LoadError: MethodError: no method matching sin(::Float64, ::Float64)
Closest candidates are:
  sin(::T<:Union{Float32, Float64}) where T<:Union{Float32, Float64} at special/trig.jl:30
  sin(::Real) at special/trig.jl:53
Stacktrace:
```

**Comment by asinghvi17** [comment]
Sin.(v+t)

**Comment by logankilpatrick** [comment]
Got it. This code produces no output, just want to make sure that's correct

**Comment by asinghvi17** [comment]
No you should have a scene displayed...

**Comment by logankilpatrick** [comment]
getting nothing as of now. do I need to do a `display(scene)` ?

**Comment by logankilpatrick** [comment]
that did the trick

**Comment by logankilpatrick** [comment]
Fixed!
