### ISSUE TITLE
Add docs such that people know Makie.Roate!() exists. 

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaPlots/MakieGallery.jl#87]
When you get a chance, please add docs saying that this functionality is out there. I can do this if you explain how I can add stuff to the docs. @asinghvi17

**Comment by logankilpatrick** [comment]
just edit the markdown files?

**Comment by asinghvi17** [comment]
You can create markdown files in docs/src, and add those to the appropriate place in docs/make.jl.

**Comment by logankilpatrick** [comment]
Okay, I will do it this week.

**Comment by asinghvi17** [comment]
Done
