### ISSUE TITLE
Confusion around Scene Docs

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaPlots/MakieGallery.jl#88]
http://makie.juliaplots.org/stable/basic-tutorials.html#Set-the-Scene-1

So in the docs, it shows `scene = Scene()` and then says it will be blank. 

A few lines later it says `scene = scatter(x, y, color = colors)`... 

So is the implication that a scatter plot is a scene? Or is there just not any further docs on the `Scene` ? 

Whichever is the case, can we update these docs to better reflect the situation?

**Comment by asinghvi17** [comment]
`Scene()` can be thought of as an empty constructor, `scatter(....)` creates a Scene and then plots to it, returning the Scene.

**Comment by logankilpatrick** [comment]
So is just scatter() a child of Scene() or are lines(), images(), etc. also children?  

Reason for asking is I want to use ‘resolution’ and I’m not sure if it’s possible for lines() or image().

**Comment by asinghvi17** [comment]
Yeah they just construct new scenes so you can pass scene attributes to them afaik.

**Comment by logankilpatrick** [comment]
Got it! I will try to update the docs to reflect that idea.

**Comment by logankilpatrick** [comment]
Updated Dev docs resolve my confusion!
