### ISSUE TITLE
Event trigger docs will lead to confusion. 

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaPlots/MakieGallery.jl#89]
The docs here: http://makie.juliaplots.org/stable/interaction.html#Event-triggering-1
 will cause people confusion. 

It read's as tough `push!(x, 5.0);` will reult in: 
`5.0`.... where in fact it will result in `x just got the value 5.0`.

The ';' also serves no purpose. I will update this when I get a chance this weekend.

**Comment by asinghvi17** [comment]
You'll want to check out makie.juliaplots.org/dev, which is where the latest changes are.

**Comment by logankilpatrick** [comment]
okay I will check it out.

**Comment by asinghvi17** [comment]
Fixed it in the latest deployment.
