### ISSUE TITLE
Test case for mitering of wide lines

### ISSUE THREAD

**Issue by c42f** [JuliaPlots/MakieGallery.jl#9]
XRef: https://github.com/JuliaPlots/GLMakie.jl/pull/28

Where does this fit in best?

Note that the weird result in the top center is a know issue with the miter becoming longer than the line itself. This is a corner case not fixed in the PR above (though not for want of trying). However the rest of the cases are a big improvement over current GLMakie.

```julia
# A test case for wide lines and mitering at joints

scene = Scene(resolution=(400,400))

r = 4
sep = 4*r
scatter!(scene, (sep+2*r)*[-1,-1,1,1], (sep+2*r)*[-1,1,-1,1])

for i=-1:1
    for j=-1:1
        angle = pi/2 + pi/4*i
        x = r*[-cos(angle/2),0,-cos(angle/2)]
        y = r*[-sin(angle/2),0,sin(angle/2)]

        linewidth = 40 * 2.0^j
        lines!(scene, x .+ sep*i, y .+ sep*j, color=RGBAf0(0,0,0,0.5), linewidth=linewidth)
        lines!(scene, x .+ sep*i, y .+ sep*j, color=:red)
    end
end

scene
```

![wide_lines](https://user-images.githubusercontent.com/601473/53151544-372adf80-35ff-11e9-943b-5a991fce832b.png)

**Comment by c42f** [comment]
By the way, this test case also reveals that the antialiasing of the ends of line segments is currently broken. A minor issue, but it's there.

**Comment by SimonDanisch** [comment]
This is in the test suite :)
