### ISSUE TITLE
Add Docs and example on how to use a Button

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaPlots/MakieGallery.jl#97]
I want to try and use a button but there are no examples.

**Comment by asinghvi17** [comment]
`button(text)`
Creates a button which can be clicked.
On click, the button increments its `clicks` field by one.
For example:
```julia
scene = button("click me please")
lift(scene[end].clicks) do clicks
    # your function here
end

**Comment by logankilpatrick** [comment]
Sweet! Thanks. This helps a lot.

**Comment by logankilpatrick** [comment]
I tested with 
```
b1 = button("Test Button")
      lift(scene[end].clicks) do clicks
            println("Button was clicked!")
      end
```
 and I got 
```ERROR: LoadError: KeyError: key :clicks not found
Stacktrace:```

**Comment by asinghvi17** [comment]
You need to lift b1 not scene

**Comment by logankilpatrick** [comment]
ha, my bad. Want me to write this up for the docs [here?](http://makie.juliaplots.org/dev/interaction.html#Button-1)

**Comment by asinghvi17** [comment]
Go for it, thanks!
